//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime createTime { get; set; }
        public System.DateTime modifyTime { get; set; }
        public string detail { get; set; }
        public string writer { get; set; }
        public int ClickVol { get; set; }
    }
}
