//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public int question_id { get; set; }
        public int test_id { get; set; }
        public string question_name { get; set; }
        public string question_chooseA { get; set; }
        public string question_chooseB { get; set; }
        public string question_chooseC { get; set; }
        public string question_chooseD { get; set; }
        public string question_answer { get; set; }
    }
}
