//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TestInfo
    {
        public int test_id { get; set; }
        [Required]
        [DisplayName("试卷名称")]
        public string test_name { get; set; }
        [Required]
        [DisplayName("测试时长(分钟)")]
        public int test_time { get; set; }
        [Required]
        [DisplayName("试卷备注信息")]
        public string test_info { get; set; }
    }
}
