//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }
        [Required]
        [DisplayName("用户名")]
        public string username { get; set; }
        [Required]
        [DisplayName("密码")]
        public string password { get; set; }
        [DisplayName("身份")]
        public int type { get; set; }
        [Required]
        [DisplayName("邮箱")]
        public string email { get; set; }
        [Required]
        [DisplayName("电话")]
        public string phone { get; set; }
        [DisplayName("头像")]
        public string imagePath { get; set; }
        [DisplayName("学校")]
        public string school { get; set; }
        [DisplayName("注册时间")]
        public System.DateTime registime { get; set; }
    }
}
