//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudyEntities : DbContext
    {
        public StudyEntities()
            : base("name=StudyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<Student_test> Student_test { get; set; }
        public virtual DbSet<TestInfo> TestInfo { get; set; }
    }
}
